### PR TITLE
WIP: Use FileIgnoreConfig from talismanRC for scan mode

### PR DESCRIPTION
**Pull request by tinamthomas**

### CODE REVIEW

**Comment by svishwanath-tw** [comment]
This is a bad idea.
`scopes`, `allowed_patterns` and `custom_patterns` are okay to be migrated directly
We won't know which commit matches which file version, so taking the file ignore configs directly from the default commit-hook is a bad idea.

**Comment by Hackl0us** [comment]
I don't think this is a bad idea, actually, I think I have the similar requirements.

If I would like to do a full scan on CI/CD pipeline based on the current files, but not all commit history. 
The current version of talisman will scan all commits even if the issues have already been fixed and make the pipeline failed.

Could you please provide a feature that can do a full scan on the current code based on the talisman configuration? I think this would be a better solution in CI/CD pipeline.

Like "--no-git" option in [_gitleaks_](https://github.com/zricethezav/gitleaks#detect)

**Comment by svishwanath-tw** [comment]
@Hackl0us : There is an option to scan only the latest commit using the `--ignoreHistory` flag Look at https://github.com/thoughtworks/talisman#talisman-as-a-cli-utility.

**Comment by Hackl0us** [comment]
@svishwanath-tw Thank you for your quick reply, I've noticed this flag. It seems that the scan will not read the configuration file `.talismanrc`. Are there any ways to do a full scan base on the configuration file?

**Pull request closed without merging**
