### PR TITLE
Binary size reduction

### PR DESCRIPTION
**Pull request by dcRUSTy**
https://github.com/thoughtworks/talisman/issues/195

### CODE REVIEW

**Comment by svishwanath-tw** [comment]
Great work.
The only/main thing I had in mind when I created the size reduction issue was that the dictionary words list is compiled in into the binary raw and uncompressed, and that leads to at last 3MB bloat.
I had read about UPX in passing, but saw that it gave little to no help.
I have 2 questions:
1. Are the newly generated binaries usable ? i.e. working on the intended OS without glitch
2. What is the reduction in size achieved ?

**Comment by dcRUSTy** [comment]
> What is the reduction in size achieved ?

Using Default settings with **default** algorithm binaries were on average **51.94% small**
Using Default settings with **LZMA** algorithm binaries were on average **58.59% small** What i observed it compressed faster and even better
upx_1

> Are the newly generated binaries usable ? i.e. working on the intended OS without glitch

upx_2

Binaries should work https://upx.github.io/ https://github.com/upx/upx UPX has been in existence since very long (1998)

**Comment by svishwanath-tw** [comment]
I can test darwin binaries, @harinee can check windows ones and linux ones can be checked on any machine.
I'm not sure how to do all these tests on travis ci though.

**Comment by harinee** [comment]
This great! Thanks @dcRUSTy 
@vhasus from the screenshot, looks like @dcRUSTy is using a windows machine. So we should be good with that.

**Review by svishwanath-tw — APPROVED** [review]

**Comment by dcRUSTy** [comment]
Tried something for travis-ci to check if compressed binaries run on target OS

But since https://docs.travis-ci.com/user/using-workspaces/ is in BETA leaving it for future.

image


Dummy yml file

`language: go
go:
- stable
jobs:
  include:
  - stage: Build on Linux
    script:
    - env GOOS=darwin GOARCH=amd64 go build main.go
    - sudo apt-get -y install upx-ucl
    - upx main
    workspaces:
      create:
        name: ws1
        paths:
        - main   
  - stage: Test on Mac
    workspaces:
      use:
      - ws1
    os: osx
    script:
    - ./main`

**Pull request merged**
