### PR TITLE
Talisman hook script ignore talisman upgrade based on variable (#211)

### PR DESCRIPTION
**Pull request by tinamthomas**
* set TALISMAN_UPGRADE_TIMEOUT for upgrade timeout(seconds). Default = 10 secs
* set TALISMAN_SKIP_UPGRADE to true to skip upgrade

### CODE REVIEW

**Comment by dcRUSTy** [comment]
https://github.com/thoughtworks/talisman/blob/master/global_install_scripts/talisman_hook_script.bash#L50 this line sends only HTTP HEAD request which is hardly of few KB's what if it succeeds in 10 second and it gets stuck while downloading binary 10MB+

**Comment by harinee** [comment]
@tinamthomas I have a few questions and comments about the upgrade timeout:
1. Have you tested how much time upgrade takes currently, across different environments/network bandwidths/OS? Is a blanket '10 secs' a good benchmark to assume a timeout threshold?
2. When a timeout occurs, we should show a message to call that out and mention that the user should perform an upgrade manually

**Comment by svishwanath-tw** [comment]
The 10 seconds should be used as a timeout to establish connection and nothing else. (ie. `--connect-timeout` and not `--max-timeout`).

More information can be found here : https://ec.haxx.se/usingcurl/usingcurl-timeouts.

If HEAD request hangs for 10s. The upgrade should probably be aborted.
The idea is to fail early instead of hang for 1 minute (curl's default) during the HEAD request to figure out the version.

This was a problem reported by a user that worked in a network restricted environment where the connection would never have worked, but the build would hang for every invocation of talisman --scan.

**Comment by tinamthomas** [comment]
@svishwanath-tw, updated the script to use --connect-timeout. If the connect-timeout exceeds the time, the version will not be fetched and download will be skipped.

**Comment by tinamthomas** [comment]
@harinee , script updated to print accordingly if update fails, but I think your MR to fix the update should be merged first

**Pull request merged**
