### PR TITLE
Encapsulate check function with content-type

### PR DESCRIPTION
**Pull request by aswinkarthik**
Minor refactoring to contentType enum. Encapsulated the check function with the type instead of a separate struct.

### CODE REVIEW

**Comment by dineshba** [comment]
Return type of `getCheckFn` can be `fn`

**Comment by svishwanath-tw** [comment]
Create 2 separate types with 3 implementations of check function.
Replace conditionals with polymorphism ...

**Comment by svishwanath-tw** [comment]
@dineshba and @aswinkarthik , if there isn't going to be any more action on this PR, i'd like to close it.

**Comment by aswinkarthik** [comment]
@svishwanath-tw  I will update it based on your feedback and push.

**Comment by svishwanath-tw** [comment]
It has been close to a month now. I'm closing out this PR. Please re-open if you wish to merge.

**Pull request closed without merging**
