### PR TITLE
Use TalismanRC in scan mode. #274

### PR DESCRIPTION
**Pull request by svishwanath-tw**

### CODE REVIEW

**Comment by svishwanath-tw** [comment]
@harinee , @dineshba , @tinamthomas : What do you folks think about this change ?

I'm unsure how to deal with file checksums in talismanrc 
* a single file could have multiple checksums in a git history
* a file could be renamed over the course of commits, talisman detects each such change and checksums them differently (ie. checksum = sha256(filepath.bytes + content.bytes)

**Comment by harinee** [comment]
I would have imagined a completely different key for scanning related settings. Scanning functions differently as it would be checking all the commit history, not just the current diff.
The reason we had checksums for individual boxes was because we need to make sure the current user reviews for the file for the current diff.
In scanning, we should have global ignores IMO, with no checksums, just spitting out warning in the report on which files were ignored.
Let me know if that made sense. We could have a call about it.

**Comment by dineshba** [comment]
```In scanning, we should have global ignores IMO, with no checksums, just spitting out warning in the report on which files were ignored.``` I agree with @harinee ... If we want to ignore some file, looks we have to completely ignore it during scan.

May be we can provide list of checksums allowed for particular file. In this case, we need to provide a way to easily calculate the list of checksums for a particular file. So that in future scans can creates error/warning as new checksum may not be added. Thoughts ?

**Comment by svishwanath-tw** [comment]
@harinee @dineshba : The separate config for scan mode makes sense
@dineshba : I did think about a list of checksums approach too, but then wondered if it was overkill

**Comment by svishwanath-tw** [comment]
The changes in this PR are for moving to GH actions and away from Travis CI.

I wasn't able to make releases because Travis builds were becoming slow and migration for TW org account wasn't trivial.

I'm closing this PR and creating a new one in its place.

**Pull request closed without merging**
