### PR TITLE
feature-proposal: ignore only certain detectors on a file

### PR DESCRIPTION
**Pull request by flosell**
Depending on your use-case, some of talismans detectors tend to produce false positives. Currently, we can only ignore the whole file in those cases while some other detectors might still be useful on this file. 

For example: 
* `init-environment.sh` currently triggers the the `\.?env` pattern (which in this case is a false-positive)
* I'd still love to be alerted if I accidentally added my AWS credentials to the script

This PR would add comments to the `.talismanignore` file that can be used to disable only certain detectors: 

```
# .talismanignore
init-environment.sh # ignore:filename
public-key.pem # normal comments don't change behavior, they disable all detectors
```

What do you think? 

If this sounds like a good addition, we could extend this by making the detectors more fine-grained.

### CODE REVIEW

**Comment by vishwas-tw** [comment]
Hi @flosell ,

Many thanks for this well thought out PR.

The need for file-specific detector exclusions (/inclusions) definitely exists.
Im concerned about assigning too many responsibilities to .talismanignore.

I'm wondering if  we can introduce a configuration file that addresses all things related to talisman (say a .talismanconfig or .talismanrc), without overloading .talismanignore. This file could be yaml, json, etc .

**Comment by flosell** [comment]
Hi @vishwas-tw 

thanks for picking up maintainership! I almost forgot this PR existed :) 

I see the reasoning for switching to a more powerful configuration language and looks like there are a few issues (#47, #39) that would profit from it. 

However, there are also complexities introduced both conceptually and implementation-wise: 
What's the migration path? Are both formats going to live side-by-side or is one replacing the other? If side-by-side, which one takes precedence? If it's a hard migration, how do people know they need to migrate to a different config? Are we going to provide tools to help with that? 

To me, the current PR feels like a smooth, non-breaking addition that doesn't make it much harder migrating to a different config format later on. I'd be happy to work on this going forward ether way but maybe it makes sense to get some value out of this PR and split the config format into a separate discussion? 

Let me know what you think.

**Comment by flosell** [comment]
Hi @svishwanath-tw, 

I would expect the commit to be blocked since `acceptance_test.go` contains suspicious content (which is not ignored) so I'm guessing you are referring to the `init-environment.sh was ignored by .talismanignore` message. I agree this message is a bit strange in this context, we should probably improve this. 

Three options I could think of: 
* Make the message more explicit (something like `init-environment.sh was ignored by .talismanignore for the following detectors: filename`)
* Skip the `was ignored [...]` message altogether if there were other errors found in the same file
* Report ignored files only if they also match the detector to allow making the message even more explicit (`The file name %q failed checks against the pattern %s but was explicitly ignored by .talismanignore`)

The first option is probably easiest to implement and least invasive. The other two I'd guess are a bit more complicated and are a bigger change to the existing behaviour. 

What do you think?

**Comment by flosell** [comment]
Hi @svishwanath-tw, 

I would expect the commit to be blocked since `acceptance_test.go` contains suspicious content (which is not ignored) so I'm guessing you are referring to the `init-environment.sh was ignored by .talismanignore` message. I agree this message is a bit strange in this context, we should probably improve this. 

Three options I could think of: 
* Make the message more explicit (something like `init-environment.sh was ignored by .talismanignore for the following detectors: filename`)
* Skip the `was ignored [...]` message altogether if there were other errors found in the same file
* Report ignored files only if they also match the detector to allow making the message even more explicit (`The file name %q failed checks against the pattern %s but was explicitly ignored by .talismanignore`)

The first option is probably easiest to implement and least invasive. The other two I'd guess are a bit more complicated and are a bigger change to the existing behaviour. 

What do you think?

**Comment by flosell** [comment]
Hi @svishwanath-tw, 

I would expect the commit to be blocked since `acceptance_test.go` contains suspicious content (which is not ignored) so I'm guessing you are referring to the `init-environment.sh was ignored by .talismanignore` message. I agree this message is a bit strange in this context, we should probably improve this. 

Three options I could think of: 
* Make the message more explicit (something like `init-environment.sh was ignored by .talismanignore for the following detectors: filename`)
* Skip the `was ignored [...]` message altogether if there were other errors found in the same file
* Report ignored files only if they also match the detector to allow making the message even more explicit (`The file name %q failed checks against the pattern %s but was explicitly ignored by .talismanignore`)

The first option is probably easiest to implement and least invasive. The other two I'd guess are a bit more complicated and are a bigger change to the existing behaviour. 

What do you think?

**Comment by flosell** [comment]
Hi @svishwanath-tw, 

I would expect the commit to be blocked since `acceptance_test.go` contains suspicious content (which is not ignored) so I'm guessing you are referring to the `init-environment.sh was ignored by .talismanignore` message. I agree this message is a bit strange in this context, we should probably improve this. 

Three options I could think of: 
* Make the message more explicit (something like `init-environment.sh was ignored by .talismanignore for the following detectors: filename`)
* Skip the `was ignored [...]` message altogether if there were other errors found in the same file
* Report ignored files only if they also match the detector to allow making the message even more explicit (`The file name %q failed checks against the pattern %s but was explicitly ignored by .talismanignore`)

The first option is probably easiest to implement and least invasive. The other two I'd guess are a bit more complicated and are a bigger change to the existing behaviour. 

What do you think?

**Comment by flosell** [comment]
Hi @svishwanath-tw, 

I would expect the commit to be blocked since `acceptance_test.go` contains suspicious content (which is not ignored) so I'm guessing you are referring to the `init-environment.sh was ignored by .talismanignore` message. I agree this message is a bit strange in this context, we should probably improve this. 

Three options I could think of: 
* Make the message more explicit (something like `init-environment.sh was ignored by .talismanignore for the following detectors: filename`)
* Skip the `was ignored [...]` message altogether if there were other errors found in the same file
* Report ignored files only if they also match the detector to allow making the message even more explicit (`The file name %q failed checks against the pattern %s but was explicitly ignored by .talismanignore`)

The first option is probably easiest to implement and least invasive. The other two I'd guess are a bit more complicated and are a bigger change to the existing behaviour. 

What do you think?

**Comment by flosell** [comment]
Hi @svishwanath-tw, 

I would expect the commit to be blocked since `acceptance_test.go` contains suspicious content (which is not ignored) so I'm guessing you are referring to the `init-environment.sh was ignored by .talismanignore` message. I agree this message is a bit strange in this context, we should probably improve this. 

Three options I could think of: 
* Make the message more explicit (something like `init-environment.sh was ignored by .talismanignore for the following detectors: filename`)
* Skip the `was ignored [...]` message altogether if there were other errors found in the same file
* Report ignored files only if they also match the detector to allow making the message even more explicit (`The file name %q failed checks against the pattern %s but was explicitly ignored by .talismanignore`)

The first option is probably easiest to implement and least invasive. The other two I'd guess are a bit more complicated and are a bigger change to the existing behaviour. 

What do you think?

**Comment by flosell** [comment]
Hi @svishwanath-tw, 

I would expect the commit to be blocked since `acceptance_test.go` contains suspicious content (which is not ignored) so I'm guessing you are referring to the `init-environment.sh was ignored by .talismanignore` message. I agree this message is a bit strange in this context, we should probably improve this. 

Three options I could think of: 
* Make the message more explicit (something like `init-environment.sh was ignored by .talismanignore for the following detectors: filename`)
* Skip the `was ignored [...]` message altogether if there were other errors found in the same file
* Report ignored files only if they also match the detector to allow making the message even more explicit (`The file name %q failed checks against the pattern %s but was explicitly ignored by .talismanignore`)

The first option is probably easiest to implement and least invasive. The other two I'd guess are a bit more complicated and are a bigger change to the existing behaviour. 

What do you think?

**Comment by flosell** [comment]
Hi @svishwanath-tw, 

I would expect the commit to be blocked since `acceptance_test.go` contains suspicious content (which is not ignored) so I'm guessing you are referring to the `init-environment.sh was ignored by .talismanignore` message. I agree this message is a bit strange in this context, we should probably improve this. 

Three options I could think of: 
* Make the message more explicit (something like `init-environment.sh was ignored by .talismanignore for the following detectors: filename`)
* Skip the `was ignored [...]` message altogether if there were other errors found in the same file
* Report ignored files only if they also match the detector to allow making the message even more explicit (`The file name %q failed checks against the pattern %s but was explicitly ignored by .talismanignore`)

The first option is probably easiest to implement and least invasive. The other two I'd guess are a bit more complicated and are a bigger change to the existing behaviour. 

What do you think?

**Comment by flosell** [comment]
Hi @svishwanath-tw, 

I would expect the commit to be blocked since `acceptance_test.go` contains suspicious content (which is not ignored) so I'm guessing you are referring to the `init-environment.sh was ignored by .talismanignore` message. I agree this message is a bit strange in this context, we should probably improve this. 

Three options I could think of: 
* Make the message more explicit (something like `init-environment.sh was ignored by .talismanignore for the following detectors: filename`)
* Skip the `was ignored [...]` message altogether if there were other errors found in the same file
* Report ignored files only if they also match the detector to allow making the message even more explicit (`The file name %q failed checks against the pattern %s but was explicitly ignored by .talismanignore`)

The first option is probably easiest to implement and least invasive. The other two I'd guess are a bit more complicated and are a bigger change to the existing behaviour. 

What do you think?

**Comment by flosell** [comment]
Hi @svishwanath-tw, 

I would expect the commit to be blocked since `acceptance_test.go` contains suspicious content (which is not ignored) so I'm guessing you are referring to the `init-environment.sh was ignored by .talismanignore` message. I agree this message is a bit strange in this context, we should probably improve this. 

Three options I could think of: 
* Make the message more explicit (something like `init-environment.sh was ignored by .talismanignore for the following detectors: filename`)
* Skip the `was ignored [...]` message altogether if there were other errors found in the same file
* Report ignored files only if they also match the detector to allow making the message even more explicit (`The file name %q failed checks against the pattern %s but was explicitly ignored by .talismanignore`)

The first option is probably easiest to implement and least invasive. The other two I'd guess are a bit more complicated and are a bigger change to the existing behaviour. 

What do you think?

**Comment by flosell** [comment]
Hi @svishwanath-tw, 

I would expect the commit to be blocked since `acceptance_test.go` contains suspicious content (which is not ignored) so I'm guessing you are referring to the `init-environment.sh was ignored by .talismanignore` message. I agree this message is a bit strange in this context, we should probably improve this. 

Three options I could think of: 
* Make the message more explicit (something like `init-environment.sh was ignored by .talismanignore for the following detectors: filename`)
* Skip the `was ignored [...]` message altogether if there were other errors found in the same file
* Report ignored files only if they also match the detector to allow making the message even more explicit (`The file name %q failed checks against the pattern %s but was explicitly ignored by .talismanignore`)

The first option is probably easiest to implement and least invasive. The other two I'd guess are a bit more complicated and are a bigger change to the existing behaviour. 

What do you think?

**Comment by flosell** [comment]
Hi @svishwanath-tw, 

I would expect the commit to be blocked since `acceptance_test.go` contains suspicious content (which is not ignored) so I'm guessing you are referring to the `init-environment.sh was ignored by .talismanignore` message. I agree this message is a bit strange in this context, we should probably improve this. 

Three options I could think of: 
* Make the message more explicit (something like `init-environment.sh was ignored by .talismanignore for the following detectors: filename`)
* Skip the `was ignored [...]` message altogether if there were other errors found in the same file
* Report ignored files only if they also match the detector to allow making the message even more explicit (`The file name %q failed checks against the pattern %s but was explicitly ignored by .talismanignore`)

The first option is probably easiest to implement and least invasive. The other two I'd guess are a bit more complicated and are a bigger change to the existing behaviour. 

What do you think?

**Comment by flosell** [comment]
Hi @svishwanath-tw, 

I would expect the commit to be blocked since `acceptance_test.go` contains suspicious content (which is not ignored) so I'm guessing you are referring to the `init-environment.sh was ignored by .talismanignore` message. I agree this message is a bit strange in this context, we should probably improve this. 

Three options I could think of: 
* Make the message more explicit (something like `init-environment.sh was ignored by .talismanignore for the following detectors: filename`)
* Skip the `was ignored [...]` message altogether if there were other errors found in the same file
* Report ignored files only if they also match the detector to allow making the message even more explicit (`The file name %q failed checks against the pattern %s but was explicitly ignored by .talismanignore`)

The first option is probably easiest to implement and least invasive. The other two I'd guess are a bit more complicated and are a bigger change to the existing behaviour. 

What do you think?

**Comment by flosell** [comment]
Hi @svishwanath-tw, 

I would expect the commit to be blocked since `acceptance_test.go` contains suspicious content (which is not ignored) so I'm guessing you are referring to the `init-environment.sh was ignored by .talismanignore` message. I agree this message is a bit strange in this context, we should probably improve this. 

Three options I could think of: 
* Make the message more explicit (something like `init-environment.sh was ignored by .talismanignore for the following detectors: filename`)
* Skip the `was ignored [...]` message altogether if there were other errors found in the same file
* Report ignored files only if they also match the detector to allow making the message even more explicit (`The file name %q failed checks against the pattern %s but was explicitly ignored by .talismanignore`)

The first option is probably easiest to implement and least invasive. The other two I'd guess are a bit more complicated and are a bigger change to the existing behaviour. 

What do you think?

**Comment by flosell** [comment]
Hi @svishwanath-tw, 

I would expect the commit to be blocked since `acceptance_test.go` contains suspicious content (which is not ignored) so I'm guessing you are referring to the `init-environment.sh was ignored by .talismanignore` message. I agree this message is a bit strange in this context, we should probably improve this. 

Three options I could think of: 
* Make the message more explicit (something like `init-environment.sh was ignored by .talismanignore for the following detectors: filename`)
* Skip the `was ignored [...]` message altogether if there were other errors found in the same file
* Report ignored files only if they also match the detector to allow making the message even more explicit (`The file name %q failed checks against the pattern %s but was explicitly ignored by .talismanignore`)

The first option is probably easiest to implement and least invasive. The other two I'd guess are a bit more complicated and are a bigger change to the existing behaviour. 

What do you think?

**Comment by svishwanath-tw** [comment]
Hey @flosell,
 Option 1 should suffice for now imo.
Option 3 is the most appealing.
I'll go ahead and create an issue for option 3 if that works for you.

**Comment by flosell** [comment]
Sounds good to me! I just added an implementation for option 1, output for your scenario now looks like this: 

```
$ git push origin master
The following errors were detected in init-environment.sh
	 Expected file to not to contain base64 or hex encoded texts such as: "accessKey=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
The following files were ignored:
	init-environment.sh was ignored by .talismanignore for the following detectors: filename
```

**Comment by svishwanath-tw** [comment]
Hey @flosell 
It works and I'm going ahead with the merge.
Although something to think about ('./foo' and 'foo' are being treated differently by .talismanignore)

**Pull request merged**
