### PR TITLE
Inform user if their talisman build is older than 'N' days(way tooooo old)

### PR DESCRIPTION
**Pull request by dcRUSTy**

### CODE REVIEW

**Comment by dcRUSTy** [comment]
@svishwanath-tw suggestions?

**Comment by svishwanath-tw** [comment]
@dcRUSTy : What happens when there is no new release of talisman for >60 days ?

**Comment by dcRUSTy** [comment]
> 
> 
> What happens when there is no new release of talisman for >60 days ?

Then user will know project is not under active development.
60 days was a random thought... How many days would be better?

**Comment by harinee** [comment]
@dcRUSTy What is the motivation behind this?
Is this to inform folks with TALISMAN_SKIP_UPGRADE set that they may be behind?
If at all showing a warning, why base it on time and not number of newer releases? The frequency of showing the message could also be annoying if someone knows they skipped upgrade on purpose

**Comment by svishwanath-tw** [comment]
> > What happens when there is no new release of talisman for >60 days ?
> 
> Then user will know project is not under active development.
> 60 days was a random thought... How many days would be better?

At my last $client : There was a cli published for use by employees.
The CLI had an update check feature that used 2 pieces of info from the server, latest version number and a whether the update was mandatory.
If currentVersion != latestVersion show warning to user let them upgrade if they feel like it.
If mandatory, no choice for end-user. Force them to update before successfully running CLI.

**Comment by dcRUSTy** [comment]
> 
> 
> @dcRUSTy What is the motivation behind this?

This is for worst case.
So that user knows he has (very?) old version. be it forgotten TALISMAN_SKIP_UPGRADE or some bug in update functionality or Firewall restriction.

> Is this to inform folks with TALISMAN_SKIP_UPGRADE set that they may be behind?

This too.
> If at all showing a warning, why base it on time and not number of newer releases? Such as "You are using an older version of Talisman which is 5 releases behind" or something on those lines.

for 'x' releases behind unrestricted network may be required and bug prone.

> The frequency of showing the message could also be annoying if someone knows they skipped upgrade on purpose

Umm....  for a case when user forgets that they `skipped upgrade on purpose`

**Comment by dineshba** [comment]
I prefer this 
```
If currentVersion != latestVersion show warning to user let them upgrade if they feel like it.
```

Already we are doing in git hooks shell script, we can do as part of golang code also (in the main.go)

In golang code, even we can show warning if there is a patch version
and force upgrade if there is a minor/major version

**Comment by harinee** [comment]
I suggest a mix of both:
Check if user is not on LatestVersion || currentVersion<v1.7 (because that's when we fixed auto-upgrade) 
Also check if the user was shown a message >60 days ago
then
  suggestUpgrade
  recordDateOfShowingMessage

**Comment by dcRUSTy** [comment]
These were the cases i thought for this PR
Case 1 - Given a user has talisman installed and don't have internet connection how can they know if they are having an age old  version of talisman or not. https://github.com/thoughtworks/talisman/issues/247
Case 2 - Auto upgrade/Version checking logic(or endpoint) has broken before and it can (definitely?) break in future.
Case 3 - Darwin 386 build are no longer generated... surely something will happen in future for any other architecture on any other OS https://github.com/thoughtworks/talisman/pull/234

We can change 60 days to 365 days or any big number... I don't find the internet dependent version checking feature that reliable... and this feature is only for edge cases

**Pull request closed without merging**
