### PR TITLE
Remove github actions config

### PR DESCRIPTION
**Pull request by svishwanath-tw**

### CODE REVIEW

**Comment by dineshba** [comment]
Why are we removing it ? Any particular reason?

**Comment by svishwanath-tw** [comment]
I was testing out GH actions
I don't see a pressing need to move to it right away.
Build seems to be failing because of path issues
You are welcome to fix it, but I don't see a value in doing so right now

**Comment by dineshba** [comment]
I am also not seeing any value now. So cool with removing it now.

**Comment by dineshba** [comment]
Looks only @svishwanath-tw can merge this PR. I think because of https://github.com/github/hub/issues/1241#issuecomment-401530226

**Comment by svishwanath-tw** [comment]
@dineshba Why not setup up a GPG key and use it to sign commits ? (for talisman at least)

**Pull request merged**
