### PR TITLE
Feature: IntelliJ IDEA Scope

### PR DESCRIPTION
**Pull request by rflaperuta**
- Feature, adding scope for IntelliJ Idea directory.

### CODE REVIEW

**Comment by svishwanath-tw** [comment]
Hi @rflaperuta 

As PR's go this is one of the finest i've seen so far.
The code changes look good to me.

I'm concerned about the practice of checking in .idea folders into the repo.
One could end up putting sensitive information (file system paths, sensitive data that could be used as part of app configurations). Given this background, I think talisman shouldn't ignore .idea/** files permanently. What do you think ?

**Comment by rflaperuta** [comment]
Hello, thanks for the feedback.

If the concern is misconfiguration leading to a leak, I agree with you.

On that matter would we need to revise exclusios for GO projects? I understand that there are some files that fall under your argument.

**Comment by svishwanath-tw** [comment]
@rflaperuta Sure thing, do mention them, we will take immediate action.

**Comment by rflaperuta** [comment]
Just take a look at the file exclusions already configured in talisman....

**Pull request closed without merging**
