### PR TITLE
Older windows support branch

### PR DESCRIPTION
**Pull request by g-prasanth**
Current operating system check, will allow only windows 10, 11, server 2016 & 2019.
There are older versions supported OSs, which version number is not MINGW64_NT-10.0*. So, I removed version check and allowed to install in all versions windows OS.

I referred [this url](https://en.wikipedia.org/wiki/Comparison_of_Microsoft_Windows_versions), to verify different kernal versions in windows.

### CODE REVIEW

**Comment by svishwanath-tw** [comment]
@g-prasanth : The only thing worrying me is how to support bug reports on older versions of windows. We will need to be able to re-create bugs or practically look for work arounds on those versions.

**Comment by g-prasanth** [comment]
The only supported Windows OSs which are not NT-10.0* are Windows 8 and 2012. And I've tested the talisman setup in both the OSs. I've tested in an unsupported windows version which is 2008R2. Hope most of the scenarios covered.

**Comment by harinee** [comment]
This is great! Thanks @g-prasanth 
When we had initially coded to support Win10, it was primarily because almost all our Windows users belonged to that version. 
My suggestion is to put in a line in the documentation (including gh-pages) to call out the versions tested and supported. I share @vhasus 's concern with older Windows, given file systems in older Windows versions could give troubles we probably haven't foreseen yet. I would suggest that we should be transparent in also explaining that in the event of triaging bugs, we would prioritise later versions of Windows (i.e. 10) over older ones. Let me know if you folks think that's fair.

**Comment by svishwanath-tw** [comment]
@g-prasanth : please update the README.md to specify which versions of windows are supported/tested like @harinee suggested

**Comment by svishwanath-tw** [comment]
@dcRUSTy, @harinee : 
If we drop support for 32 bit windows, XP will be the oldest OS talisman could run on. 
SSL version incompatibility will rule out web based installation on XP machines. 
That only leaves out windows 7.
What do you folks think about dropping support for 32 bit OSes ?

**Comment by dcRUSTy** [comment]
May be lets add a line in Readme.md that talisman binary may be compatible with older version of windows(because of golang) and thats it.... 
Lets not change installation script....
If a user knows about git hooks it wont take more than a minute to figure out how to use talisman binary and how to remove if they are facing issues.

**Comment by svishwanath-tw** [comment]
@dcRUSTy : If the idea is to overlook installations on unsupported versions, I think we should change the scripts to be past and future proof (ie. accept this PR) and put in a disclaimer stating what versions we've successfully tested talisman on.

**Comment by dcRUSTy** [comment]
ok 👍

**Comment by g-prasanth** [comment]
Thanks everyone. If any user faces issue in unsupported windows version, we don't need to troubleshoot and fix it since the OS is not supported by windows itself. But our talisman binary will work in most of the currently being used OS versions.

I will commit the disclaimer along with the tested versions.

**Comment by g-prasanth** [comment]
Sorry for the delay. I've added disclaimer in readme.

**Review by svishwanath-tw — APPROVED** [review]

**Pull request merged**
